export const EMAIL_LIST_REQUEST = 'EMAIL_LIST_REQUEST'
export const EMAIL_LIST_SUCCESS = 'EMAIL_LIST_SUCCESS'
export const EMAIL_LIST_FAIL = 'EMAIL_LIST_FAIL'

export const EMAIL_CREATE_REQUEST = 'EMAIL_CREATE_REQUEST'
export const EMAIL_CREATE_SUCCESS = 'EMAIL_CREATE_SUCCESS'
export const EMAIL_CREATE_FAIL = 'EMAIL_CREATE_FAIL'
export const EMAIL_CREATE_RESET = 'EMAIL_CREATE_RESET'
