export const IDEA_LIST_REQUEST = 'IDEA_LIST_REQUEST'
export const IDEA_LIST_SUCCESS = 'IDEA_LIST_SUCCESS'
export const IDEA_LIST_FAIL = 'IDEA_LIST_FAIL'

export const IDEA_DETAILS_REQUEST = 'IDEA_DETAILS_REQUEST'
export const IDEA_DETAILS_SUCCESS = 'IDEA_DETAILS_SUCCESS'
export const IDEA_DETAILS_FAIL = 'IDEA_DETAILS_FAIL'
export const IDEA_DETAILS_RESET = 'IDEA_DETAILS_RESET'

export const IDEA_CREATE_REQUEST = 'IDEA_CREATE_REQUEST'
export const IDEA_CREATE_SUCCESS = 'IDEA_CREATE_SUCCESS'
export const IDEA_CREATE_FAIL = 'IDEA_CREATE_FAIL'
export const IDEA_CREATE_RESET = 'IDEA_CREATE_RESET'

export const IDEA_UPDATE_REQUEST = 'IDEA_UPDATE_REQUEST'
export const IDEA_UPDATE_SUCCESS = 'IDEA_UPDATE_SUCCESS'
export const IDEA_UPDATE_FAIL = 'IDEA_UPDATE_FAIL'
export const IDEA_UPDATE_RESET = 'IDEA_UPDATE_RESET'

export const IDEA_DELETE_REQUEST = 'IDEA_DELETE_REQUEST'
export const IDEA_DELETE_SUCCESS = 'IDEA_DELETE_SUCCESS'
export const IDEA_DELETE_FAIL = 'IDEA_DELETE_FAIL'
