export const NUGGET_LIST_REQUEST = 'NUGGET_LIST_REQUEST'
export const NUGGET_LIST_SUCCESS = 'NUGGET_LIST_SUCCESS'
export const NUGGET_LIST_FAIL = 'NUGGET_LIST_FAIL'

export const NUGGET_DETAILS_REQUEST = 'NUGGET_DETAILS_REQUEST'
export const NUGGET_DETAILS_SUCCESS = 'NUGGET_DETAILS_SUCCESS'
export const NUGGET_DETAILS_FAIL = 'NUGGET_DETAILS_FAIL'
export const NUGGET_DETAILS_RESET = 'NUGGET_DETAILS_RESET'

export const NUGGET_CREATE_REQUEST = 'NUGGET_CREATE_REQUEST'
export const NUGGET_CREATE_SUCCESS = 'NUGGET_CREATE_SUCCESS'
export const NUGGET_CREATE_FAIL = 'NUGGET_CREATE_FAIL'
export const NUGGET_CREATE_RESET = 'NUGGET_CREATE_RESET'

export const NUGGET_UPDATE_REQUEST = 'NUGGET_UPDATE_REQUEST'
export const NUGGET_UPDATE_SUCCESS = 'NUGGET_UPDATE_SUCCESS'
export const NUGGET_UPDATE_FAIL = 'NUGGET_UPDATE_FAIL'
export const NUGGET_UPDATE_RESET = 'NUGGET_UPDATE_RESET'

export const NUGGET_DELETE_REQUEST = 'NUGGET_DELETE_REQUEST'
export const NUGGET_DELETE_SUCCESS = 'NUGGET_DELETE_SUCCESS'
export const NUGGET_DELETE_FAIL = 'NUGGET_DELETE_FAIL'
